### ISSUE TITLE
add code signing to release process

### ISSUE THREAD

**Issue by samcooley** [h-be/acorn-release#3]
https://electronjs.org/docs/tutorial/code-signing

**Comment by Connoropolous** [comment]
Unfortunately, after heavy research and attempts on this on Friday, it appears that one needs to be enrolled in the Apple Developer Program as an org or individual in order to do osx code signing :(
looks like it costs 140 cad / year, so I didn't proceed.
I'm guessing it's not worth it at this stage, but may down the road?

**Comment by samcooley** [comment]
Apple Developer Program added, and certification, signing and notarizing configured as part of branch for this issue and #9
